#:schema https://schemas.spinframework.dev/spin/manifest-v2/latest.json

spin_manifest_version = 2

[application]
name = "hello-wasm"
version = "0.1.0"
authors = ["edisonylee <edisonydlee@gmail.com>"]
description = "Edge streaming SSR platform"

[[trigger.http]]
route = "/hello"
component = "hello-wasm"

[component.hello-wasm]
source = "target/wasm32-wasip1/release/hello_wasm.wasm"
allowed_outbound_hosts = ["https://jsonplaceholder.typicode.com"]

[component.hello-wasm.build]
command = "cargo build -p hello-wasm --target wasm32-wasip1 --release"
watch = ["workloads/hello-wasm/src/**/*.rs", "crates/**/*.rs", "Cargo.toml"]
