spin_manifest_version = 2

[application]
name = "ecommerce-pdp"
version = "0.1.0"
description = "E-commerce Product Detail Page demonstrating streaming SSR"

[[trigger.http]]
route = "/product/..."
component = "ecommerce-pdp"

[component.ecommerce-pdp]
source = "../../target/wasm32-wasip1/release/ecommerce_pdp.wasm"
allowed_outbound_hosts = ["https://*"]

[component.ecommerce-pdp.build]
command = "cargo build --target wasm32-wasip1 --release"
